<a href="https://colab.research.google.com/github/OscarGuti17/Ejercicio-Curso/blob/main/Distancia_y_Tiempo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


distance = [100,200,400,800,1500,3000,5000,10000]
type(distance)
distance_array = np.array(distance)
distance_array

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

In [2]:
A= np.min(distance_array)
print(A)
B= np.max(distance_array)
print(B)

100
10000


In [3]:
np.mean(distance_array)

2625.0

In [4]:
np.sum(distance_array)

21000

In [5]:
np.cumsum(distance_array)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

In [6]:
np.round(distance_array)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

In [7]:
time = [10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
tiempo_array =np.array(time)
tiempo_array

array([  10.62,   21.34,   48.25,  113.43,  233.96,  506.53,  866.17,
       1757.45])

In [8]:
distance_array.dtype
tiempo_array.dtype
metros_xseg = distance_array / tiempo_array
metros_xseg

array([9.41619586, 9.37207123, 8.29015544, 7.0528079 , 6.41135237,
       5.92265019, 5.77253888, 5.69006231])

In [9]:
distance_array
distance_millas = distance_array
distance_millas
convert_mill = 0.00062
n = 0
for n in range(len(distance_array)):
      distance_millas[n] =distance_array[n]*convert_mill
distance_array

array([0, 0, 0, 0, 0, 1, 3, 6])

In [10]:
# Arreglo de tiempo
tiempo_array
tiempo_horas = tiempo_array
M = 0
for m in range(len(tiempo_horas)):
      tiempo_horas[m] = tiempo_horas[m]*3600
tiempo_horas
millas_per_hora = distance_millas / tiempo_horas
millas_per_hora

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.48393536e-07, 9.62089813e-07, 9.48343718e-07])